namespace Compressarr.Web.Dtos;

public sealed record SettingsDto(
    string HandBrakeCliPath,
    string PresetsPath,
    string HandBrakeOptions,
    bool FileBotEnabled,
    string FileBotCliPath,
    bool FileBotTvEnabled,
    string FileBotTvArgs,
    bool FileBotMovieEnabled,
    string FileBotMovieArgs,
    List<string> VidTypes,
    bool OutSameAsIn,
    string DeleteAfterConvert,
    bool MoveFiles,
    bool ClearTitleMetadata,
    int Limit,
    long MinSizeBytes,
    List<string> CompanionExtensions,
    string UnmatchedCompanionAction,
    string OnDestinationCollision,
    string LogFilePath,
    int RetentionDays,
    string PostExecCmd,
    string PostExecArgs,
    string ReportPath,
    string OpenAfterRun,
    int RepeatCount,
    bool RepeatMonitor,
    int PollIntervalSeconds,
    string QueueEtaFormat,
    ArrServiceDto Sonarr,
    ArrServiceDto Radarr,
    int WebPort,
    bool RunAtLogin,
    string BackupFolderPath,
    int BackupIntervalDays,
    int BackupRetentionDays,
    DateTimeOffset? BackupLastRunUtc);

public sealed record ArrServiceDto(bool Enabled, string Url, string ApiKey);
